/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veterinaria;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import java.net.URI;
import AppPackage.AnimationClass;
import java.awt.Desktop;
import java.util.logging.Level;
import java.util.logging.Logger;
import static veterinaria.IngresarAdmin.esEmail;

/**
 *
 * @author Armando
 */
public class Login extends javax.swing.JFrame {
    
    ConexionBD cox = new ConexionBD();
    Connection cx;
    boolean administrador = false;

    AnimationClass internet = new AnimationClass();
            
    public Login() throws ClassNotFoundException {
        
        this.cx = cox.conexion();
        this.cox = new ConexionBD();
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void internet(){
        
        try{
            
            Desktop.getDesktop().browse(URI.create( "http://127.0.0.1/scripts/bootstrap/"));
        }catch(Exception e){
            
            JOptionPane.showConfirmDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labMenu = new javax.swing.JLabel();
        labRegistrarse = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labPassword = new javax.swing.JLabel();
        labUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        sepUser = new javax.swing.JSeparator();
        sepPassword = new javax.swing.JSeparator();
        txtContraseña = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labMaximizar = new javax.swing.JLabel();
        labMinimizar = new javax.swing.JLabel();
        labInfo = new javax.swing.JLabel();
        labAdmin = new javax.swing.JLabel();
        labWeb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 188, 156)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-menú-filled-40.png"))); // NOI18N
        labMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labMenuMouseExited(evt);
            }
        });
        jPanel1.add(labMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 32, 32));

        labRegistrarse.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        labRegistrarse.setForeground(new java.awt.Color(177, 93, 100));
        labRegistrarse.setText("Registrarse");
        labRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labRegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labRegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labRegistrarseMouseExited(evt);
            }
        });
        jPanel1.add(labRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 80, 20));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 188, 156));
        jLabel4.setText("User:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        labPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-contraseña-40.png"))); // NOI18N
        labPassword.setText("jLabel5");
        jPanel1.add(labPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 45, 38));

        labUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-invitado-masculino-40.png"))); // NOI18N
        jPanel1.add(labUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 45, 38));

        txtUser.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        txtUser.setForeground(new java.awt.Color(153, 153, 153));
        txtUser.setBorder(null);
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 190, 30));
        jPanel1.add(sepUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 230, 10));
        jPanel1.add(sepPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 230, 10));

        txtContraseña.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(153, 153, 153));
        txtContraseña.setText("jPasswordField1");
        txtContraseña.setBorder(null);
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraseñaMouseClicked(evt);
            }
        });
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 190, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Enter_ON.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Enter_OFF.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Enter_OFF.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Enter_OFF.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 110, 40));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(26, 188, 156));
        jLabel7.setText("Password:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(26, 188, 156));
        jLabel8.setText("No tienes cuenta?");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 110, 20));

        labMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-cerrar-ventana-40.png"))); // NOI18N
        labMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labMaximizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labMaximizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labMaximizarMouseExited(evt);
            }
        });
        jPanel1.add(labMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 40, 40));

        labMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-minimizar-la-ventana-40.png"))); // NOI18N
        labMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labMinimizar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-minimizar-la-ventana-40 (1).png"))); // NOI18N
        labMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labMinimizarMouseExited(evt);
            }
        });
        jPanel1.add(labMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 40, 40));

        labInfo.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        labInfo.setForeground(new java.awt.Color(51, 51, 51));
        labInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-información-40.png"))); // NOI18N
        labInfo.setText("Información");
        labInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(labInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-145, 150, -1, 40));

        labAdmin.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        labAdmin.setForeground(new java.awt.Color(51, 51, 51));
        labAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-hombre-de-negocios-40 (1).png"))); // NOI18N
        labAdmin.setText("Administrador");
        labAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labAdminMouseClicked(evt);
            }
        });
        jPanel1.add(labAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(-145, 50, -1, 40));

        labWeb.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        labWeb.setForeground(new java.awt.Color(51, 51, 51));
        labWeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-internet-40.png"))); // NOI18N
        labWeb.setText("Internet");
        labWeb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labWeb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labWebMouseClicked(evt);
            }
        });
        jPanel1.add(labWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(-145, 100, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-administrador-del-hombre-150.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 76, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMinimizarMouseClicked
        // TODO add your handling code here:
        
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_labMinimizarMouseClicked

    private void labMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMaximizarMouseClicked
        // TODO add your handling code here:
        
        int dialog = JOptionPane.showConfirmDialog(null, "Deceas cerrar la ventana?", "Salir",  JOptionPane.YES_NO_OPTION);
        if( dialog == 0 ){
            
            System.exit(0);
        }
    }//GEN-LAST:event_labMaximizarMouseClicked

    private void labMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMenuMouseClicked
        // TODO add your handling code here:
        
        internet.jLabelXRight(-145, 10, 10, 5, labAdmin);
        internet.jLabelXLeft(10, -145, 10, 5, labAdmin);
        internet.jLabelXRight(-145, 10, 10, 5, labWeb);
        internet.jLabelXLeft(10, -145, 10, 5, labWeb);
        internet.jLabelXRight(-145, 10, 10, 5, labInfo);
        internet.jLabelXLeft(10, -145, 10, 5, labInfo);
    }//GEN-LAST:event_labMenuMouseClicked

    private void labWebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labWebMouseClicked
        // TODO add your handling code here:
        
        internet();
    }//GEN-LAST:event_labWebMouseClicked

    private void labMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMinimizarMouseEntered
        // TODO add your handling code here:
        labMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-minimizar-la-ventana-40 (2).png")));
    }//GEN-LAST:event_labMinimizarMouseEntered

    private void labMaximizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMaximizarMouseExited
        // TODO add your handling code here:
        
        labMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-cerrar-ventana-40.png")));
    }//GEN-LAST:event_labMaximizarMouseExited

    private void labMaximizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMaximizarMouseEntered
        // TODO add your handling code here:
        labMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-cerrar-ventana-40 (2).png")));
    }//GEN-LAST:event_labMaximizarMouseEntered

    private void labMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMinimizarMouseExited
        // TODO add your handling code here:
        labMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-minimizar-la-ventana-40.png")));
    }//GEN-LAST:event_labMinimizarMouseExited

    private void labRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labRegistrarseMouseEntered
        // TODO add your handling code here:
        
        labRegistrarse.setForeground(new java.awt.Color(255, 38, 0));
    }//GEN-LAST:event_labRegistrarseMouseEntered

    private void labRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labRegistrarseMouseExited
        // TODO add your handling code here:
        
        labRegistrarse.setForeground(new java.awt.Color(177, 93, 100));
    }//GEN-LAST:event_labRegistrarseMouseExited

    private void labMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMenuMouseEntered
        // TODO add your handling code here:
        
        labMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-menú-filled-40 (1).png")));
    }//GEN-LAST:event_labMenuMouseEntered

    private void labMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMenuMouseExited
        // TODO add your handling code here:
        
        labMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-menú-filled-40.png")));
    }//GEN-LAST:event_labMenuMouseExited

    private void txtContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMouseClicked
        // TODO add your handling code here:
        
        //txtContraseña.setText("");
        sepPassword.setForeground(new java.awt.Color(52, 152, 219));
        labPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-contraseña-40 (1).png")));
        
        //txtUser.setText("Ingresa tu Usuario");
        sepUser.setForeground(new java.awt.Color(160,160,160));
        labUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-invitado-masculino-40.png")));
    }//GEN-LAST:event_txtContraseñaMouseClicked

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        // TODO add your handling code here:
        
        //txtUser.setText("");
        sepUser.setForeground(new java.awt.Color(52, 152, 219));
        labUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-invitado-masculino-40 (1).png")));
        
        //txtContraseña.setText("***********");
        sepPassword.setForeground(new java.awt.Color(160,160,160));
        labPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-contraseña-40.png")));
    }//GEN-LAST:event_txtUserMouseClicked

    private void labRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labRegistrarseMouseClicked
        // TODO add your handling code here:
        
        IngresarUsuario objUno;
        try {
            objUno = new IngresarUsuario();
            objUno.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_labRegistrarseMouseClicked

    private void labAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labAdminMouseClicked
        // TODO add your handling code here:
        
        IngresarAdmin objUno;
        
        try {
            
            objUno = new IngresarAdmin();
            objUno.setVisible(true);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_labAdminMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        String sql = "SELECT e.Nombre, e.Email, e.Contrasena, p.Puesto FROM empleados e INNER JOIN puestos p ON idPuestoEmp = idPuestos";
        String datos[] = new String[4];
        MenuUsuario objDos;
        
        
        
        if ( esEmail(txtUser.getText())== false){
              
            JOptionPane.showMessageDialog(null,"Direccion de correo no valida"," ventana de Error",JOptionPane.WARNING_MESSAGE);
        }
        
        try{
            Statement st = null;
            st = cx.createStatement();
            ResultSet resp = st.executeQuery(sql);
            objDos = new MenuUsuario();
            while(resp.next()){
                
                datos[0] = resp.getString(1);
                datos[1] = resp.getString(2);
                datos[2] = resp.getString(3);
                datos[3] = resp.getString(4);
                //JOptionPane.showMessageDialog(null,"Bienvenido "+datos[2]+" Admin","Iniciando sesión",JOptionPane.INFORMATION_MESSAGE);
                if(txtUser.getText().equals(datos[1]) && txtContraseña.getText().equals(datos[2])){
                    
                    if(datos[3].equals("Administrador")){
                    
                        administrador = true;
                        this.setVisible(false);
                        objDos.setAdmin(administrador);
                        objDos.setVisible(true);
                    
                        JOptionPane.showMessageDialog(null,"Bienvenido "+datos[0]+" Admin","Iniciando sesión",JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        
                        this.setVisible(false);
                        objDos.setVisible(true);
                        JOptionPane.showMessageDialog(null,"Bienvenido "+datos[0],"Iniciando sesión",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    static boolean esEmail(String cadena){
    
    boolean bandera = false;
    
    bandera = cadena.matches("^[\\w-]+(\\.[\\w-]+)*@[A-Za-z0-9]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
    
    return bandera;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labAdmin;
    private javax.swing.JLabel labInfo;
    private javax.swing.JLabel labMaximizar;
    private javax.swing.JLabel labMenu;
    private javax.swing.JLabel labMinimizar;
    private javax.swing.JLabel labPassword;
    private javax.swing.JLabel labRegistrarse;
    private javax.swing.JLabel labUser;
    private javax.swing.JLabel labWeb;
    private javax.swing.JSeparator sepPassword;
    private javax.swing.JSeparator sepUser;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
